def get_brands():
    brands = [
        "Nissan",
        "Mitsubishi",
        "ВАЗ (Lada)",
        "Porsche",
        "JAC",
        "Toyota",
        "Chevrolet",
        "Volkswagen",
        "Mercedes-Benz",
        "Ford",
        "Audi",
        "Suzuki",
        "Peugeot",
        "BMW",
        "Hyundai",
        "Kia",
        "Opel",
        "Lexus",
        "Hummer",
        "Land Rover",
        "Daewoo",
        "Cadillac",
        "ГАЗ",
        "Renault",
        "Subaru",
        "Dodge",
        "Lifan",
        "УАЗ",
        "Infiniti",
        "GMC",
        "ИЖ",
        "Skoda",
        "Mazda",
        "Ravon",
        "Honda",
        "Foton",
        "Jaguar",
        "Tesla",
        "Rover",
        "Mini",
        "SsangYong",
        "Geely",
        "Great Wall",
        "Volvo",
        "Chrysler",
        "Lincoln",
        "Mercedes-Maybach",
        "Fiat",
        "Jeep",
        "Isuzu",
        "Москвич",
        "Renault Samsung",
        "Maserati",
        "Citroen",
        "Chery",
        "Bentley",
        "ЗАЗ",
        "Datsun",
        "FAW",
        "Scion",
        "BYD",
        "Seat",
        "Changan",
        "Genesis",
        "Acura",
        "Saab",
        "Lancia",
        "Haima",
        "РАФ",
        "MG",
        "Wuling",
        "Pontiac",
        "ZX",
        "Ретро-автомобили",
        "DongFeng",
        "Maybach",
        "Mercury",
        "Bugatti",
        "Daihatsu",
        "Rolls-Royce",
        "Saturn",
        "BAIC",
        "ЛуАЗ",
        "Alfa Romeo",
        "Tianye",
    ]
    return brands

def get_body_types():
    body_types = [
        'Седан',
        'Пикап',
        'кроссовер',
        'лифтбек',
        'кроссовер',
        'универсал',
        'внедорожник',
        'минивэн',
    ]
    return body_types

def get_fuel_types():
    fuel_types = [
        'бензин',
        'дизель',
        'газ',
        'гибрид',
    ]
    return fuel_types

def get_wheel_drives():
    wheel_drives = [
        'передний привод',
        'задний привод',
        'полный привод',
    ]
    return wheel_drives

def get_colors():
    colors = [
        'серебристый',
        'белый',
        'зеленый',
        'черный металлик',
        'черный',
        'серебристый металлик',
        'синий металлик',
        'синий',
        'фиолетовый металлик',
        'красный',
        'серый металлик',
        'серый',
        'голубой металлик',
        'белый металлик',
        'жёлтый металлик',
        'зеленый металлик',
        'вишня металлик',
        'бордовый',
        'золотистый',
        'бордовый металлик',
        'вишня',
        'оранжевый',
        'бежевый металлик',
        'красный металлик',
        'коричневый металлик',
        'золотистый металлик',
        'оранжевый металлик',
        'коричневый',
        'хамелеон',
        'жёлтый',
        'хамелеон металлик',
        'бирюзовый',
        'бирюзовый металлик',
        'розовый металлик',
        'бронза металлик',
        'бежевый',
        'голубой',
        'розовый',
        'бронза',
        'фиолетовый',
        'сиреневый',
        'сиреневый металлик'
    ]
    return colors
