# Generated by Django 3.1.4 on 2020-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=20)),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=1)),
                ('mileage', models.DecimalField(decimal_places=1, max_digits=7)),
                ('gear_type', models.CharField(max_length=20)),
                ('steering_wheel', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=30)),
                ('wheel_drive', models.CharField(max_length=16)),
                ('custom_clearanced', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('link', models.CharField(max_length=40)),
                ('fuel_type', models.CharField(max_length=8)),
            ],
        ),
    ]
