# Generated by Django 3.1.4 on 2020-12-21 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0002_car_favourite_mtm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='favourite_mtm',
        ),
        migrations.AddField(
            model_name='car',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
