# Generated by Django 3.1.4 on 2020-12-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20201210_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
