# Generated by Django 3.1.4 on 2020-12-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20201210_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_difference_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
