# Generated by Django 3.1.4 on 2020-12-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201221_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favourite_car',
            new_name='favourite',
        ),
    ]
